server:
  port: 8081

spring:
  application:
    name: Cart
  data:
    mongodb:
      uri: mongodb+srv://sdutta:A8T4bruLnXSdhuPc@multikart.khko0j6.mongodb.net/multikart_cart?retryWrites=true&w=majority

